# Travis Continuous Integration script for travis-ci.org

# Runs all unit tests
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script:
  mvn clean verify

# Checks for broken links in README.md
language: ruby
rvm: 2.2
before_script: gem install awesome_bot
script: awesome_bot README.md --allow-dupe --allow-redirect

